// Package failureid attaches privacy-safe correlation identifiers to runtime
// errors. The wrapper preserves errors.Is/errors.As behavior and keeps the
// human-readable error unchanged; callers choose where to display the ID.
package failureid

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"sync/atomic"
	"time"
)

const Prefix = "err-"

var fallback atomic.Uint64

type identified interface {
	FailureID() string
}

type identifiedError struct {
	id  string
	err error
}

func (e *identifiedError) Error() string     { return e.err.Error() }
func (e *identifiedError) Unwrap() error     { return e.err }
func (e *identifiedError) FailureID() string { return e.id }

// Ensure returns err with one correlation ID. Existing IDs survive wrapping
// and errors.Join, so every surface observing the same failure reports the
// same value.
func Ensure(err error) error {
	if err == nil || ID(err) != "" {
		return err
	}
	return &identifiedError{id: New(), err: err}
}

// ID returns the correlation identifier attached anywhere in err's chain.
func ID(err error) string {
	var value identified
	if errors.As(err, &value) {
		return value.FailureID()
	}
	return ""
}

// Display adds an identifier for user-facing diagnostics without changing
// Error(), structured classification, or matching semantics.
func Display(err error) string {
	if err == nil {
		return ""
	}
	if id := ID(err); id != "" {
		return fmt.Sprintf("%s\nFailure ID: %s", err.Error(), id)
	}
	return err.Error()
}

// New returns a random identifier containing no error, workspace, session,
// provider, or credential material.
func New() string {
	data := make([]byte, 8)
	if _, err := rand.Read(data); err == nil {
		return Prefix + hex.EncodeToString(data)
	}
	value := uint64(time.Now().UnixNano()) ^ fallback.Add(1)
	return fmt.Sprintf("%s%016x", Prefix, value)
}

// Valid recognizes only identifiers generated by this package.
func Valid(id string) bool {
	if len(id) != len(Prefix)+16 || !strings.HasPrefix(id, Prefix) {
		return false
	}
	for _, c := range id[len(Prefix):] {
		if !strings.ContainsRune("0123456789abcdef", c) {
			return false
		}
	}
	return true
}
