package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"github.com/robert-mcdermott/collomia/internal/version"
)

// schemaDialect is the JSON Schema version the generated contract speaks.
const schemaDialect = "https://json-schema.org/draft/2020-12/schema"

// SchemaFileName is the schema written beside a configuration file, and
// SchemaReference is how a configuration file refers to it. The reference is
// relative so that a configuration directory stays movable and works with no
// network at all.
const (
	SchemaFileName  = "collomia.schema.json"
	SchemaReference = "./" + SchemaFileName
)

// JSONSchema returns the configuration contract as JSON Schema 2020-12.
//
// It is generated from the structs rather than maintained beside them, because
// a hand-written copy of a 121-field surface is a copy that drifts — which is
// exactly how docs/FEATURES.md came to document a mandatory-audit posture that
// never existed. Field names and types come from reflection, so they cannot
// disagree with the loader; enumerated values come from the vocabularies in
// vocabulary.go, so they cannot disagree with the validator; and defaults are
// read out of Defaults() itself.
//
// Descriptions are the one part supplied by hand, and
// TestEveryConfigurationFieldIsDescribed fails on a field that has none.
func JSONSchema() []byte {
	builder := &schemaBuilder{defs: map[string]map[string]any{}}
	root := builder.object(reflect.TypeFor[Config](), "Config", reflect.ValueOf(Defaults()))
	root["$schema"] = schemaDialect
	root["$id"] = "https://collomia.dev/schema/config-v" + fmt.Sprint(CurrentSchemaVersion) + ".json"
	root["title"] = "Collomia configuration"
	root["description"] = "Configuration for the Collomia terminal coding agent, generated by " +
		version.Short() + ". Regenerate with `collo schema config` after upgrading."
	if len(builder.defs) > 0 {
		defs := make(map[string]any, len(builder.defs))
		for name, def := range builder.defs {
			defs[name] = def
		}
		root["$defs"] = defs
	}
	encoded, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		// Unreachable: every value placed in the tree is a plain map, slice,
		// string, number, or bool. Panicking beats returning a broken schema
		// that an editor would silently ignore.
		panic("config: generating the configuration schema: " + err.Error())
	}
	return append(encoded, '\n')
}

type schemaBuilder struct {
	defs map[string]map[string]any
}

// ref returns a reference to a named definition, generating it on first use.
// variant names a narrower reading of the same Go type — a delegated agent's
// rules are []Rule in Go but may only prompt or deny, and a schema that let an
// editor offer "allow" there would be offering a value the loader rejects.
func (b *schemaBuilder) ref(typ reflect.Type, variant string, defaults reflect.Value) map[string]any {
	name := typ.Name()
	if variant != "" {
		name = variant
	}
	if _, seen := b.defs[name]; !seen {
		// Reserve the name before recursing so a self-referential type would
		// terminate rather than recurse forever.
		b.defs[name] = map[string]any{}
		b.defs[name] = b.object(typ, name, defaults)
	}
	return map[string]any{"$ref": "#/$defs/" + name}
}

// object renders one struct. defaults, when valid, is the value Defaults()
// holds at this position, so the schema's defaults are read from the same
// function the loader starts from rather than transcribed beside it.
func (b *schemaBuilder) object(typ reflect.Type, defName string, defaults reflect.Value) map[string]any {
	properties := map[string]any{}
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		jsonName, ok := jsonFieldName(field)
		if !ok {
			continue
		}
		key := fieldKey{defName, jsonName}
		schema := b.value(field.Type, key, childDefaults(defaults, i))
		if description := describeField(typ.Name(), defName, jsonName); description != "" {
			schema["description"] = description
		}
		if enum := enumFor(key); len(enum) > 0 {
			schema["enum"] = toAny(enum)
		}
		if bound, ok := boundFor(key); ok {
			for constraint, limit := range bound {
				schema[constraint] = limit
			}
		}
		if value := defaultAt(defaults, i); value != nil {
			schema["default"] = value
		}
		properties[jsonName] = schema
	}
	object := map[string]any{
		"type":       "object",
		"properties": properties,
		// Everything an editor would otherwise infer about presence is stated
		// rather than derived; see requiredFields for why nothing at the root
		// can be required at all.
		// Unknown keys are flagged. This deliberately matches
		// `collo config validate --strict` rather than the ordinary loader,
		// which ignores them: a misspelled field that silently does nothing is
		// the failure an editor is best placed to catch, and catching it while
		// the line is being typed is the whole point of shipping a schema.
		"additionalProperties": false,
	}
	if required := requiredFields[defName]; len(required) > 0 {
		object["required"] = toAny(required)
	}
	return object
}

// value renders the schema for one field's type.
func (b *schemaBuilder) value(typ reflect.Type, key fieldKey, defaults reflect.Value) map[string]any {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	switch typ.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice, reflect.Array:
		// The element carries the parent's key so a slice of structs can still
		// select a variant, and no element has a singleton default.
		return map[string]any{"type": "array", "items": b.value(typ.Elem(), key, reflect.Value{})}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": b.value(typ.Elem(), key, reflect.Value{})}
	case reflect.Struct:
		return b.ref(typ, variantFor(key), defaults)
	default:
		// No configuration field has another kind, and a silent "any" would
		// turn an unmodelled field into one the editor never checks.
		panic("config: no schema mapping for " + typ.String())
	}
}

// fieldKey identifies one field of one definition. The definition name rather
// than the Go type name is what is keyed, so a variant can carry its own
// enumeration without a second Go type existing for it.
type fieldKey struct {
	def   string
	field string
}

// jsonFieldName returns the wire name of a field, or false for one that never
// reaches the file.
//
// Note what is deliberately *not* derived here: whether the field is required.
// The obvious source is the absence of `omitempty`, and it is wrong — a
// boolean that defaults to true omits the tag so that `false` still serializes,
// not because the field must be present. options.mouse and
// permissions.allow_outside_workspace are both in that position, and a schema
// built that way would have made an editor demand them. Requirements are
// stated explicitly in requiredFields instead, and checked against the
// validator.
func jsonFieldName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" || tag == "" || !field.IsExported() {
		return "", false
	}
	name := strings.Split(tag, ",")[0]
	if name == "" || name == "-" {
		return "", false
	}
	return name, true
}

// defaultAt reads the value Defaults() holds for one field, when the caller is
// on a path that has a singleton default at all. Zero values are omitted: a
// declared `"default": 0` beside an optional field says nothing, while a
// declared `"default": true` on options.mouse is load-bearing, and only the
// second is non-zero.
func defaultAt(defaults reflect.Value, index int) any {
	if !defaults.IsValid() || defaults.Kind() != reflect.Struct {
		return nil
	}
	field := defaults.Field(index)
	if !field.CanInterface() || field.IsZero() {
		return nil
	}
	switch field.Kind() {
	case reflect.String:
		return field.String()
	case reflect.Bool:
		return field.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return field.Int()
	case reflect.Float32, reflect.Float64:
		return field.Float()
	case reflect.Slice:
		if field.Type().Elem().Kind() != reflect.String {
			return nil
		}
		return toAny(field.Interface().([]string))
	default:
		// Nested structs and maps carry their defaults on their own fields,
		// which the recursion reaches directly.
		return nil
	}
}

// childDefaults descends into a nested struct's defaults, so options.mouse can
// report that it defaults to true rather than losing it at the boundary
// between Config and Options.
func childDefaults(defaults reflect.Value, index int) reflect.Value {
	if !defaults.IsValid() || defaults.Kind() != reflect.Struct {
		return reflect.Value{}
	}
	field := defaults.Field(index)
	for field.Kind() == reflect.Pointer {
		if field.IsNil() {
			return reflect.Value{}
		}
		field = field.Elem()
	}
	if field.Kind() != reflect.Struct {
		return reflect.Value{}
	}
	return field
}

func toAny(values []string) []any {
	out := make([]any, len(values))
	for i, value := range values {
		out[i] = value
	}
	return out
}
